Use Cake's IFileSystem for read/write operations instead of System.IO.File
cake-contrib/Cake.FileHelpers pull request #118
Opened 2023-02-17 20:52 UTC by ap0llo

## Description

In all file aliases, use Cake's IFileSystem abstraction instead of using System.IO.File. 
This enables testing of tasks that use the file aliases by mocking IFileSystem.

The FileTouch() alias continues to use System.IO.File since there is no API in IFileSystem that allows setting the last write time.

## Related Issue
This PR fixes #117

## Motivation and Context
See #117. This enables mocking of the file system in tests for tasks

## How Has This Been Tested?
All tests in the project are still passing

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes. (*Covered by existing tests*)
- [x] All new and existing tests passed.

2023-02-20 03:23 UTC, augustoproiete requested changes
Thanks for the PR @ap0llo! Concept ACK and overall LGTM. Added a couple of minor comments/requests

2023-02-20 03:23 UTC, augustoproiete commented on src/Cake.FileHelpers/FileHelpers.cs
> +        private static StreamReader CreateStreamReader(ICakeContext context, FilePath file, Encoding? encoding = null)
```suggestion

        private static StreamReader CreateStreamReader(ICakeContext context, FilePath file, Encoding encoding = null)
```

We don't yet support nullable references in this addin, so let's remove these for now.

2023-02-20 03:23 UTC, augustoproiete commented on src/Cake.FileHelpers/FileHelpers.cs
> +        private static StreamWriter CreateStreamWriter(ICakeContext context, FilePath file, FileMode mode, Encoding? encoding = null)
```suggestion
        private static StreamWriter CreateStreamWriter(ICakeContext context, FilePath file, FileMode mode, Encoding encoding = null)
```

We don't yet support nullable references in this addin, so let's remove these for now.

2023-02-20 03:23 UTC, augustoproiete commented on src/Cake.FileHelpers/FileHelpers.cs
> +            var stream = context.FileSystem.GetFile(file).OpenRead();
```suggestion
            var stream = context.FileSystem.GetFile(file.MakeAbsolute(context.Environment)).OpenRead();
```

Let's expand the path to an absolute path to keep the original behavior that is now removed from the aliases

2023-02-20 03:23 UTC, augustoproiete commented on src/Cake.FileHelpers/FileHelpers.cs
> +            var stream = context.FileSystem.GetFile(file).Open(mode);
```suggestion
            var stream = context.FileSystem.GetFile(file.MakeAbsolute(context.Environment)).Open(mode);
```

Let's expand the path to an absolute path to keep the original behavior that is now removed from the aliases

2023-02-20 20:45 UTC, ap0llo commented
Thanks for your review! I applied your suggestions, please let me know if there is anything else you'd like me to adapt.

2023-02-21 04:39 UTC, augustoproiete approved these changes
LGTM

2023-02-21 04:43 UTC, merged